services:
  text-exporter:
    build:
      context: .
      dockerfile: ./image/text-exporter/Dockerfile
    volumes:
      - promfile:/app/data

    ports:
      - ${BIND-9014}:9014
    entrypoint:
    - /usr/bin/textfile_exporter
    - -p
    - ./data
    restart: on-failure:10
  lsusb:
    build:
      context: .
      dockerfile: ./image/lsusb/Dockerfile
    hostname: ${HOSTNAME:-CHANGEME}
    env_file:
      - .env
    volumes:
      - /dev:/dev:ro
      - promfile:/app/data
      - ./run.sh:/app/run.sh:ro
    entrypoint: "./run.sh"
    restart: on-failure:10

volumes:
  promfile:
